import com.mysql.cj.jdbc.Driver;

import java.sql.*;

public class jdbcLecture {
    public static void main(String[] args) throws SQLException {
        Config config = new Config();
        //Instantiate the MySQL Driver to register to the built in Java Driver Manager.
        DriverManager.registerDriver(new Driver());

        //Connect to the database by providing the URL, user, and the password we want to connect as.
        //NOTICE- in the URL you need to specify which database you are using. codeup_test_db is used below.
        Connection connection = DriverManager.getConnection(
                config.getUrl(),
                config.getUser(),
                config.getPassword());

        //Create a statement object to execute queries.
        Statement statement = connection.createStatement();

        //We can use the Statement object to make our queries.
        //statement.execute("DELETE FROM albums WHERE id = 4");

        //executeUpdate: returns the number of rows affected
        //statement.executeUpdate("INSERT INTO albums (artist, album_name, release_date, genre, sales) VALUES('Nelly Furtado', 'Loose', 2006, 'Dance-pop, hip hop, R&B', 12.5)");

        //executeQuery: returns a ResultSet object
        //statement.executeQuery("SELECT * FROM albums");

        //Handling the results with the ResultSet object
        String selectQuery = "SELECT * FROM albums";
        ResultSet rs = statement.executeQuery(selectQuery);

        //By calling the .next() method we can iterate over the rows.
        //The method will return as true as long as there are rows left in our results.
        //Therefore, the most common way to handle the results is to use a while loop.

        while(rs.next()){
            System.out.println("Here's and album: ");
            System.out.println(" id: " + rs.getLong("id"));
            System.out.println(" artist: " + rs.getString("artist"));
            System.out.println(" album name: " + rs.getString("album_name"));
        }

        //INSERT query
//        String insertQuery = "INSERT INTO albums (artist, album_name, release_date, genre, sales) VALUES('Nelly Furtado', 'Loose', 2006, 'Dance-pop, hip hop, R&B', 12.5)";

        //For executeUpdate method, we can have two arguments:
        //First, is the Query String we want to execute.
        //Second, is a constant from the Statement Object.
        //This gives us access to the ID's that are auto generated by the database

//        statement.executeUpdate(insertQuery, Statement.RETURN_GENERATED_KEYS);

        //We can then use the getGeneratedKeys() method on teh ResultSet object which will hold any ID's generated by the database.
//        ResultSet rsKeys = statement.getGeneratedKeys();

//        if(rsKeys.next()){
//            System.out.println("Inserted a new record! New ID: " + rsKeys.getLong(1));
//        }
    }
}
